# Generated by Django 3.2.9 on 2021-12-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='star_rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
