# Generated by Django 3.2.9 on 2021-12-20 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('prep_time', models.CharField(default=None, max_length=200)),
                ('difficulty', models.CharField(default=None, max_length=200)),
                ('description', models.CharField(default=None, max_length=2000)),
                ('kcal', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('saturates', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('sugars', models.IntegerField()),
                ('fibre', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('salt', models.IntegerField()),
                ('ingredients_one', models.CharField(default=None, max_length=100)),
                ('ingredients_two', models.CharField(blank=True, default=None, max_length=100)),
                ('ingredients_three', models.CharField(blank=True, default=None, max_length=100)),
                ('ingredients_four', models.CharField(blank=True, default=None, max_length=100)),
                ('ingredients_five', models.CharField(blank=True, default=None, max_length=100)),
                ('instructions_one', models.CharField(default=None, max_length=300)),
                ('instructions_two', models.CharField(blank=True, default=None, max_length=300)),
                ('instructions_three', models.CharField(blank=True, default=None, max_length=300)),
                ('instructions_four', models.CharField(blank=True, default=None, max_length=300)),
                ('instructions_five', models.CharField(blank=True, default=None, max_length=300)),
                ('potential_price', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('picture', models.CharField(default=None, max_length=500)),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
